INSERT INTO Card (front, back) VALUES
                                   ('Astonishing', 'Şaşırtıcı'),
                                   ('Consequence', 'Sonuç'),
                                   ('Vulnerable', 'Savunmasız'),
                                   ('Incredible', 'İnanılmaz'),
                                   ('Comprehensive', 'Kapsamlı'),
                                   ('Ambiguous', 'Belirsiz'),
                                   ('Cautiously', 'Dikkatlice'),
                                   ('Inevitable', 'Kaçınılmaz'),
                                   ('Perception', 'Algı'),
                                   ('Noteworthy', 'Dikkate değer'),
                                   ('Facilitate', 'Kolaylaştırmak'),
                                   ('Diminish', 'Azaltmak'),
                                   ('Simultaneously', 'Eşzamanlı olarak'),
                                   ('Subsequently', 'Sonradan'),
                                   ('Controversial', 'Tartışmalı'),
                                   ('Accumulate', 'Birikmek'),
                                   ('Conscientious', 'Vicdanlı'),
                                   ('Phenomenon', 'Olay'),
                                   ('Exaggerate', 'Abartmak'),
                                   ('Implicate', 'Bulaştırmak');
INSERT INTO Deck (name) VALUES
                                   ('English-Turkish');
INSERT INTO Deck_Cards (deck_id, cards_id) VALUES
                                   (1, 1),
                                   (1, 2),
                                   (1, 3),
                                   (1, 4),
                                   (1, 5),
                                   (1, 6),
                                   (1, 7),
                                   (1, 8),
                                   (1, 9),
                                   (1, 10),
                                   (1, 11),
                                   (1, 12),
                                   (1, 13),
                                   (1, 14),
                                   (1, 15),
                                   (1, 16),
                                   (1, 17),
                                   (1, 18),
                                   (1, 19),
                                   (1, 20);

INSERT INTO member (id,username,password) VALUES (1,'furkan','{noop}123456789')