INSERT INTO Card (front, back, occurrences) VALUES
                                   ('Astonishing', 'Şaşırtıcı',0),
                                   ('Consequence', 'Sonuç',0),
                                   ('Vulnerable', 'Savunmasız',0),
                                   ('Incredible', 'İnanılmaz',0),
                                   ('Comprehensive', 'Kapsamlı',0),
                                   ('Ambiguous', 'Belirsiz',0),
                                   ('Cautiously', 'Dikkatlice',0),
                                   ('Inevitable', 'Kaçınılmaz',0),
                                   ('Perception', 'Algı',0),
                                   ('Noteworthy', 'Dikkate değer',0),
                                   ('Facilitate', 'Kolaylaştırmak',0),
                                   ('Diminish', 'Azaltmak',0),
                                   ('Simultaneously', 'Eşzamanlı olarak',0),
                                   ('Subsequently', 'Sonradan',0),
                                   ('Controversial', 'Tartışmalı',0),
                                   ('Accumulate', 'Birikmek',0),
                                   ('Conscientious', 'Vicdanlı',0),
                                   ('Phenomenon', 'Olay',0),
                                   ('Exaggerate', 'Abartmak',0),
                                   ('Implicate', 'Bulaştırmak',0);
INSERT INTO Deck (name) VALUES
                                   ('English-Turkish');
INSERT INTO Deck_Cards (deck_id, cards_id) VALUES
                                   (1, 1),
                                   (1, 2),
                                   (1, 3),
                                   (1, 4),
                                   (1, 5),
                                   (1, 6),
                                   (1, 7),
                                   (1, 8),
                                   (1, 9),
                                   (1, 10),
                                   (1, 11),
                                   (1, 12),
                                   (1, 13),
                                   (1, 14),
                                   (1, 15),
                                   (1, 16),
                                   (1, 17),
                                   (1, 18),
                                   (1, 19),
                                   (1, 20);